name: Image Build
on: 
  push:
    tags:
      - '[0-9]*'
    branches-ignore: '*'

jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # needed for pushing to ghcr.io
      id-token: write  # for OIDC login (if needed)

    steps:
      - name: Checkout recursive
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

